# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-access-control"
BBFILE_PATTERN_meta-access-control = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-access-control = "6"

LAYERDEPENDS_meta-access-control = "core"
LAYERSERIES_COMPAT_meta-access-control = "scarthgap"
